const PdtList = [
  {
    name: "LAPTOP",
    category: "ELECTRONIC",
    quantity: 12,
    price: 500,
    image: "/image/laptop.jpg",
    description: "A powerful laptop with 16GB RAM and SSD storage.",
  },
  {
    name: "MAKEUP",
    category: "FASHION",
    quantity: 10,
    price: 50,
    image: "/image/makeup.jpg",
    description: "High-quality makeup set with vibrant shades.",
  },
  {
    name: "MOUSE",
    category: "ELECTRONIC",
    quantity: 18,
    price: 80,
    image: "/image/mouse.jpeg",
    description: "Wireless mouse with precision tracking.",
  },
  {
    name: "EARING",
    category: "ACCESSORIES",
    quantity: 15,
    price: 10,
    image: "/image/earing.jpg",
    description: "Elegant stud earrings for all occasions.",
  },
  {
    name: "SHIRT",
    category: "FASHION",
    quantity: 20,
    price: 30,
    image: "/image/shirt.jpg",
    description: "Stylish cotton shirt for all-day comfort.",
  },
  {
    name: "HEADPHONE",
    category: "ELECTRONIC",
    quantity: 17,
    price: 100,
    image: "/image/headphone.jpeg",
    description: "Noise-cancelling headphones with crystal-clear sound.",
  },
  {
    name: "WATCH",
    category: "ACCESSORIES",
    quantity: 24,
    price: 150,
    image: "/image/watch.jpg",
    description: "Sleek analog watch that combines fashion and function.",
  },
];

export default PdtList;